name: Daily Stock Report (DeepSeek)

on:
  schedule:
    # 每周周二到周六，中国时间早上7点 = UTC时间前一天晚上23点
    #- cron: '0 23 * * 2,3,4,5,6'
  workflow_dispatch: # 允许手动点击按钮测试

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python report.py
